### ISSUE TITLE
move to blindnet.dev

### ISSUE THREAD

**Issue by noelmace** [blindnet-io/blindnet.dev#15]
- [x] @noelmace confirm the budget for buying the blindnet.dev domain name with @Vuk-BN 
- [x] @noelmace confirm deadline & feasibility with @filipblnt 
- [x] buy blindnet.dev domain name
- [x] move docs.blindnet.io to blindnet.dev
- [x] make sure old URL are correctly redirected
- [x] replace "blindnet-docs" and "dev portal" by "blindnet.dev" / ".dev" / "dev"  / "develop" everywhere

**Comment by m4rk055** [comment]
https://blindnet.dev is live and https://docs.blindnet.io redirects to it.

Where should we update the domain besides the website and the dashboard?

**Comment by noelmace** [comment]
EVERYWHEEEERE :laughing:

I'm currently working on a PR to prepare for next Monday's announcement so I'll update the "brand" name while I'm at it, I believe it should be enough if you also update the domain and "brand" on the website and dashboard.

**Comment by m4rk055** [comment]
> replace "blindnet-docs" and "dev portal" by "blindnet.dev" / ".dev" / "dev" / "develop" everywhere

Replaced on the website and the dashboard.
Are there any promotional materials or social profiles that need to be updated?

**Comment by noelmace** [comment]
@m4rk055 If you could just replace "Developer Portal" with "Developers" in the menu of blindnet.io, then, I believe we're good. Thx

![image](https://user-images.githubusercontent.com/7578400/174601501-82b573e3-47d7-4b87-b540-fa1ae5615c3a.png)

**Comment by noelmace** [comment]
### :warning: Important notice <br /> regarding the blindnet.dev brand and the associated idiom "Developer Portal"

> ping all @blindnet-io/blindnet

***blindnet.dev*** is a brand by itself. This is the only idiom you need to talk about the blindnet.dev (formerly docs.blindnert.io) website, whatever the context.

Please avoid using _"Developer Portal"_. The word "portal" should only be used in a complete sentence when explaining what blindnet.dev is, if and only if necessary, and **NEVER** as an idiom.

We **MUST ALWAYS** use **"blindnet.dev"** by default, and **"Developers"** (or similar wordings) in clear blindnet context (e.g. main, menu on blindnet.io)
