### ISSUE TITLE
Use internal 404 page

### ISSUE THREAD

**Issue by noelmace** [blindnet-io/blindnet.dev#44]
## Problem

Right now, calling an inexistent path on blindnet.dev lead to an Azure 404 page:

![image](https://user-images.githubusercontent.com/7578400/189703667-a6c52d9f-b361-49d2-831f-51613fd03bb6.png)

## Proposed Solution

We need instead to correctly redirect to Docusaurus so its internal 404 page is shown instead:

![image](https://user-images.githubusercontent.com/7578400/189703875-7c4b7a90-15e5-4042-9d9d-cf4836bc9d8d.png)

## How to conduct the change

I believe this is just something to configure in Azure Static Apps.

@m4rk055 let me know if you want to address this issue. Otherwise, I'd be happy to.

**Comment by m4rk055** [comment]
Done. [staticwebapp.config.json](https://github.com/blindnet-io/blindnet.dev/blob/main/staticwebapp.config.json) with the defined fallback route was needed by Azure Static Web Apps.
